name: Add Template to Bucket
on:
  push:
    branches:
      - master
    paths:
      - 'rubrik_cloudon.template'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
   
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Copy Template  
      env:
        FILE: ./rubrik_cloudon.template
        AWS_REGION: 'us-west-1'
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_KEY: ${{ secrets.S3_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        pip install --quiet --no-cache-dir awscli
        aws s3 cp ${FILE} s3://${S3_BUCKET}/${S3_KEY}
